version: "3.8"

services:
    web:
        tty: true
        stdin_open: true
        build:
            context: "."
            dockerfile: ./docker/Dockerfile
        volumes:
        - ./test:/var/www/html/test
        ports:
        - 3000:3000
